### ISSUE TITLE
Make Kelda's DNS server case insensitive

### ISSUE THREAD

**Issue by luise** [kelda/kelda#1327]
Kelda's DNS server should be case insensitive, because many applications assume this is the case -- for instance, Node.js lowercases hostnames before attempting to resolve them in DNS. This means that any hostnames with capital letters will fail to resolve when given to a Node app. Kelda's DNS server code is in `minion/network/dns.go`.

**Comment by kklin** [comment]
I've written a simple blueprint that shows this problem:

```
// This blueprint deploys a container that prints "Pass" if it successfully
// resolves a Kelda hostname with a mutated case.
const kelda = require('kelda');

const machine = new kelda.Machine({ provider: 'Amazon' });
const infra = new kelda.Infrastructure(machine, machine);

const container = new kelda.Container('exampleHostnameWithCaps', 'alpine');

const lowerCaseHostname = container.getHostname().toLowerCase();
if (container.getHostname() === lowerCaseHostname) {
  console.error("The test hostname is already lowercase.")
  process.exit(1);
}

container.command = [
  'sh', '-c',
    `if getent hosts ${lowerCaseHostname}; then ` +
      'echo Pass; ' +
    'else ' +
      'echo Fail; ' +
    'fi;' +
    'tail -f /dev/null',
];
container.deploy(infra);
```

Right now, running the blueprint then running `kelda logs exampleHostnameWithCaps` (to get the output of the test container) shows "Fail". If this issue is fixed, the logs should have "Pass".

What the blueprint is doing is creating a container whose hostname has capital letters, but then resolving the hostname to an IP with an all-lowercase version of the hostname.

**Comment by Ch3ck** [comment]
I'll clone and code and try to build then I'll look at the files with the logs.

**Comment by Ch3ck** [comment]
@kklin You can close this now.
