### ISSUE TITLE
Deploying from a Private Repository?

### ISSUE THREAD

**Issue by simplygreatwork** [kelda/kelda#1357]
I'm currently working with this example: https://github.com/kelda/nodejs How do I supply credentials to be able to clone from a private repo?

Thanks,
Philip

**Comment by kklin** [comment]
Hi Philip!

Unfortunately there's no great way to do that right now. There's a hacky way that _should_ work, and there's a secure solution that's on our roadmap for next month.

The hacky solution is to embed the credentials for pulling the repo in the Dockerfile. If your private repository is on GitHub you can generate a [personal access token](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/) and use that to authenticate. IIRC the tokens have pretty fine-grained permissions management, so I think you can restrict it to just pull access for your repo. Once you've generated the token, you can pass it to the `git clone` command [here](https://github.com/kelda/nodejs/blob/master/node.js#L39). I haven't used this personally, but according to Stackoverflow you can pass the password [like so](https://stackoverflow.com/questions/10054318/how-to-provide-username-and-password-when-run-git-clone-gitremote-git).

This should be pretty secure since we use TLS to send the Dockerfile to the cloud and the machines in the cloud are using private networking; however, we don't treat Dockerfiles as secret, so the password might still get logged somewhere.

The upcoming solution is to allow passing credentials to `docker pull`. Once that's in, you would build a Docker image based on your private repository, push it to a private DockerHub repo, and give Kelda the credentials to pull the private image.

Definitely let us know if you have any other questions or feedback! Feel free to open more GitHub issues, or join our [Slack](http://slack.kelda.io/)!
